// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2bI8Ea9L6bPZmbrW8ibluIvB_C2wu-k',
    appId: '1:1069420824924:web:5fb26f9464ffa40f299999',
    messagingSenderId: '1069420824924',
    projectId: 'assignment4-e5e96',
    authDomain: 'assignment4-e5e96.firebaseapp.com',
    storageBucket: 'assignment4-e5e96.firebasestorage.app',
    measurementId: 'G-NDKWJCS9LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjyvUjaXtnHrO76fjUHADjxKXot8DH7uk',
    appId: '1:1069420824924:android:1aef0998514d9cae299999',
    messagingSenderId: '1069420824924',
    projectId: 'assignment4-e5e96',
    storageBucket: 'assignment4-e5e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQ8nKKLfie5xmFwjoMCDNRZRaJ1rmaao',
    appId: '1:1069420824924:ios:d954f43bd03d8777299999',
    messagingSenderId: '1069420824924',
    projectId: 'assignment4-e5e96',
    storageBucket: 'assignment4-e5e96.firebasestorage.app',
    iosBundleId: 'com.example.assignment4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnQ8nKKLfie5xmFwjoMCDNRZRaJ1rmaao',
    appId: '1:1069420824924:ios:d954f43bd03d8777299999',
    messagingSenderId: '1069420824924',
    projectId: 'assignment4-e5e96',
    storageBucket: 'assignment4-e5e96.firebasestorage.app',
    iosBundleId: 'com.example.assignment4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl2bI8Ea9L6bPZmbrW8ibluIvB_C2wu-k',
    appId: '1:1069420824924:web:21a38ef51694ea96299999',
    messagingSenderId: '1069420824924',
    projectId: 'assignment4-e5e96',
    authDomain: 'assignment4-e5e96.firebaseapp.com',
    storageBucket: 'assignment4-e5e96.firebasestorage.app',
    measurementId: 'G-WFB56X9387',
  );
}
